- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Doe mij maar {{ aantal | default('een') }} {{ tekst | default('ontstopper') }} !"
      tags:
      - test

