- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Doe mij maar {{ aantal }} {{ tekst }} !"
      tags:
      - test
    - pause:
        minutes: 5
      tags:
      - hoi
    
